/**
 * Compile authored content (content/**) into validated records.
 *
 * Pure: takes already-read JSON files and returns records + issues. File-system access
 * lives in ./io.ts, so this module is tested with in-memory fixtures.
 *
 * Content layout (paths relative to content/):
 *   taxonomy/systems.json          authored system records   (./taxonomy.ts)
 *   taxonomy/regions.json          authored region records   (./taxonomy.ts)
 *   sources/*.json                 sourceSchema
 *   structures/_inventory/*.json   imported drafts (regenerated by content:inventory)
 *   structures/**                  authored structures or overlays on inventory drafts (./merge.ts)
 *   relations/**                   relationSchema
 *   lessons/**                     lessonSchema
 *   questions/**                   questionSchema
 *   reviews/**                     reviewRecordSchema (human review events only)
 *   scope/**                       scopeTargetSchema (the scope matrix)
 * Every file holds either one record object or an array of records.
 */
import type { z } from 'zod'
import {
  assetSchema,
  lessonSchema,
  questionSchema,
  relationSchema,
  reviewRecordSchema,
  scopeTargetSchema,
  sourceSchema,
  structureSchema,
  type Lesson,
  type ModelAsset,
  type Question,
  type RegionRecord,
  type Relation,
  type ReviewRecord,
  type ScopeTarget,
  type Source,
  type Structure,
  type SystemRecord,
} from '../../../src/core/schema.ts'
import { error, formatZodError, safeParseTr, warning, type Issue } from './issues.ts'
import { isPlainObject, mergeOverlay } from './merge.ts'
import {
  authoredRegionSchema,
  authoredSystemSchema,
  toRegionRecord,
  toSystemRecord,
  type AuthoredRegion,
  type AuthoredSystem,
} from './taxonomy.ts'

export interface ContentFile {
  /** Path relative to the content root, '/' separated (e.g. "sources/fma.json"). */
  path: string
  data: unknown
}

export interface CompileInput {
  files: readonly ContentFile[]
  /** public/data/assets.json from the model pipeline (path relative to the repo root), if present. */
  assets?: ContentFile | null
  /** Prefix added to content paths in issue locations. Default "content/". */
  contentPrefix?: string
}

export type RecordKind =
  | 'system'
  | 'region'
  | 'structure'
  | 'relation'
  | 'source'
  | 'asset'
  | 'lesson'
  | 'question'
  | 'review'
  | 'scope'

export interface CompiledContent {
  systems: SystemRecord[]
  regions: RegionRecord[]
  /** Authored taxonomy incl. per-language name verification (not part of the core contract). */
  authoredSystems: AuthoredSystem[]
  authoredRegions: AuthoredRegion[]
  structures: Structure[]
  relations: Relation[]
  sources: Source[]
  assets: ModelAsset[]
  lessons: Lesson[]
  questions: Question[]
  reviews: ReviewRecord[]
  scope: ScopeTarget[]
  /** Files each record came from, keyed `${kind}:${id}` (overlays list base file first). */
  origins: Map<string, string[]>
}

export interface CompileResult {
  content: CompiledContent
  issues: Issue[]
}

type Collection =
  | 'systems'
  | 'regions'
  | 'sources'
  | 'inventory'
  | 'structures'
  | 'relations'
  | 'lessons'
  | 'questions'
  | 'reviews'
  | 'scope'

export function classifyContentPath(path: string): Collection | null {
  if (path === 'taxonomy/systems.json') return 'systems'
  if (path === 'taxonomy/regions.json') return 'regions'
  if (path.startsWith('structures/_inventory/')) return 'inventory'
  const top = path.split('/')[0]
  switch (top) {
    case 'sources':
    case 'structures':
    case 'relations':
    case 'lessons':
    case 'questions':
    case 'reviews':
    case 'scope':
      return top
    default:
      return null
  }
}

export function emptyContent(): CompiledContent {
  return {
    systems: [],
    regions: [],
    authoredSystems: [],
    authoredRegions: [],
    structures: [],
    relations: [],
    sources: [],
    assets: [],
    lessons: [],
    questions: [],
    reviews: [],
    scope: [],
    origins: new Map(),
  }
}

function recordsOf(file: ContentFile, fileLabel: string, issues: Issue[]): unknown[] {
  if (Array.isArray(file.data)) return file.data
  if (isPlainObject(file.data)) return [file.data]
  issues.push(error('file_format', 'Dosya bir kayıt nesnesi ya da kayıt dizisi içermeli.', { file: fileLabel }))
  return []
}

function rawId(raw: unknown): string | undefined {
  return isPlainObject(raw) && typeof raw.id === 'string' ? raw.id : undefined
}

function schemaIssue(err: z.ZodError, index: number, file: string, id: string | undefined): Issue {
  return error('schema', `Kayıt #${index + 1} geçersiz — ${formatZodError(err).join('; ')}`, { file, recordId: id })
}

export function compileContent(input: CompileInput): CompileResult {
  const prefix = input.contentPrefix ?? 'content/'
  const issues: Issue[] = []
  const content = emptyContent()
  const groups = new Map<Collection, ContentFile[]>()

  const sorted = [...input.files].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
  for (const f of sorted) {
    const col = classifyContentPath(f.path)
    // terminology/: inputs of `npm run content:terms` (e.g. Turkish name candidates), not content.
    if (!col && f.path.startsWith('terminology/')) continue
    if (!col) {
      issues.push(warning('unknown_file', 'Bu konumdaki dosya hiçbir içerik türüne ait değil; derlemeye alınmadı.', { file: prefix + f.path }))
      continue
    }
    const list = groups.get(col)
    if (list) list.push(f)
    else groups.set(col, [f])
  }

  const label = (f: ContentFile) => prefix + f.path

  function parseAll<S extends z.ZodType<{ id: string }>>(kind: RecordKind, col: Collection, schema: S): z.output<S>[] {
    const out: z.output<S>[] = []
    const seen = new Map<string, string>()
    for (const f of groups.get(col) ?? []) {
      recordsOf(f, label(f), issues).forEach((raw, i) => {
        const r = safeParseTr(schema, raw)
        if (!r.success) {
          issues.push(schemaIssue(r.error, i, label(f), rawId(raw)))
          return
        }
        const id = r.data.id
        const first = seen.get(id)
        if (first !== undefined) {
          issues.push(error('duplicate_id', `"${id}" kimliği birden fazla kez tanımlanmış (ilk tanım: ${first}).`, { file: label(f), recordId: id }))
          return
        }
        seen.set(id, label(f))
        content.origins.set(`${kind}:${id}`, [label(f)])
        out.push(r.data)
      })
    }
    return out
  }

  // Taxonomy -----------------------------------------------------------------
  content.authoredSystems = parseAll('system', 'systems', authoredSystemSchema)
  content.systems = content.authoredSystems.map(toSystemRecord)
  content.authoredRegions = parseAll('region', 'regions', authoredRegionSchema)
  content.regions = content.authoredRegions.map(toRegionRecord)

  // Sources and other flat collections -----------------------------------------
  content.sources = parseAll('source', 'sources', sourceSchema)
  content.relations = parseAll('relation', 'relations', relationSchema)
  content.lessons = parseAll('lesson', 'lessons', lessonSchema)
  content.questions = parseAll('question', 'questions', questionSchema)
  content.reviews = parseAll('review', 'reviews', reviewRecordSchema)
  content.scope = parseAll('scope', 'scope', scopeTargetSchema)

  // Structures: inventory drafts + authored overlays -------------------------
  /**
   * Overlays for one id may come from several files (e.g. generated terminology + an audit
   * note); they are merged in path order. Repeating an id inside one file is an error.
   */
  const collectRaw = (col: Collection, mergeAcrossFiles = false) => {
    const map = new Map<string, { raw: Record<string, unknown>; file: string }>()
    const files = [...(groups.get(col) ?? [])].sort((a, b) => (label(a) < label(b) ? -1 : label(a) > label(b) ? 1 : 0))
    for (const f of files) {
      recordsOf(f, label(f), issues).forEach((raw, i) => {
        const id = rawId(raw)
        if (!isPlainObject(raw) || id === undefined) {
          issues.push(error('overlay_without_id', `Kayıt #${i + 1} bir "id" alanı içermiyor.`, { file: label(f) }))
          return
        }
        const prev = map.get(id)
        if (prev && (!mergeAcrossFiles || prev.file.split(' + ').includes(label(f)))) {
          issues.push(error('duplicate_id', `"${id}" kimliği birden fazla kez tanımlanmış (ilk tanım: ${prev.file}).`, { file: label(f), recordId: id }))
          return
        }
        if (prev) {
          map.set(id, { raw: mergeOverlay(prev.raw, raw) as Record<string, unknown>, file: `${prev.file} + ${label(f)}` })
          return
        }
        map.set(id, { raw, file: label(f) })
      })
    }
    return map
  }
  const base = collectRaw('inventory')
  const overlays = collectRaw('structures', true)
  const ids = [...new Set([...base.keys(), ...overlays.keys()])].sort()
  for (const id of ids) {
    const b = base.get(id)
    const o = overlays.get(id)
    const raw = b && o ? mergeOverlay(b.raw, o.raw) : (o?.raw ?? b?.raw)
    const files = [b?.file, o?.file].filter((x): x is string => x !== undefined)
    const r = safeParseTr(structureSchema, raw)
    if (!r.success) {
      issues.push(
        error('schema', `Yapı kaydı geçersiz${b && o ? ' (içe aktarılan taslak + ek birleştirildikten sonra)' : ''} — ${formatZodError(r.error).join('; ')}`, {
          file: files.join(' + '),
          recordId: id,
        }),
      )
      continue
    }
    content.origins.set(`structure:${id}`, files)
    content.structures.push(r.data)
  }

  // Model assets (owned by the model pipeline; validated, never rewritten) -----
  if (input.assets) {
    const f = input.assets
    let list: unknown[] | null = null
    if (Array.isArray(f.data)) list = f.data
    else if (isPlainObject(f.data) && Array.isArray(f.data.assets)) list = f.data.assets
    if (!list) {
      issues.push(error('file_format', 'Model varlık dosyası bir dizi ya da { "assets": [...] } nesnesi olmalı.', { file: f.path }))
    } else {
      const seen = new Set<string>()
      list.forEach((raw, i) => {
        const r = safeParseTr(assetSchema, raw)
        if (!r.success) {
          issues.push(schemaIssue(r.error, i, f.path, rawId(raw)))
          return
        }
        if (seen.has(r.data.id)) {
          issues.push(error('duplicate_id', `"${r.data.id}" model varlığı birden fazla kez tanımlanmış.`, { file: f.path, recordId: r.data.id }))
          return
        }
        seen.add(r.data.id)
        content.origins.set(`asset:${r.data.id}`, [f.path])
        content.assets.push(r.data)
      })
    }
  }

  return { content, issues }
}

/** "file1 + file2" for a record, for issue locations. */
export function originOf(content: CompiledContent, kind: RecordKind, id: string): string | undefined {
  return content.origins.get(`${kind}:${id}`)?.join(' + ')
}
