/**
 * Overlay merge for structure records.
 *
 * content/structures/_inventory/*.json holds imported drafts that are regenerated by
 * `npm run content:inventory`. Authored files elsewhere under content/structures/ may
 * contain partial records ("overlays") with the same id; they are merged on top so a
 * re-import never overwrites authored work.
 *
 * Rules:
 *  - plain objects merge recursively,
 *  - arrays and scalars in the overlay replace the base value,
 *  - `null` in the overlay removes the key from the result.
 */

export function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

export function mergeOverlay(base: unknown, overlay: unknown): unknown {
  if (!isPlainObject(base) || !isPlainObject(overlay)) return overlay === null ? undefined : overlay
  const out: Record<string, unknown> = { ...base }
  for (const [key, value] of Object.entries(overlay)) {
    if (value === null) {
      delete out[key]
      continue
    }
    const merged = key in base ? mergeOverlay(base[key], value) : value
    if (merged === undefined) delete out[key]
    else out[key] = merged
  }
  return out
}
